#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/process_runner/cli'

begin
  cli = ProcessRunner::CLI.instance
  cli.parse
  cli.run
rescue StandardError => e
  raise e if $DEBUG

  warn e.message
  warn e.backtrace.join("\n")

  exit 1
end
